title: 'Using Reinforcement Learning On Tic Tac Toe'
theme: jekyll-theme-cayman
show_downloads: true
markdown: kramdown
description: 'C Sharp Demonstration of How Reinforcement Learning Works Using A Basic Game'
