theme: jekyll-theme-cayman
show_downloads: true
markdown: kramdown
tagline: 'Using Reinforcement Learning in Tic Tac Toe'
description: 'C Sharp Demonstration of How Reinforcement Learning Works Using A Basic Game'
